sudo: false

language: scala

scala:
  - 2.10.5
  - 2.11.7

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

script: sbt ++$TRAVIS_SCALA_VERSION coverage core/test coverageReport

after_success: bash <(curl -s https://codecov.io/bash)
